# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BabelStyler
                                 A QGIS plugin
 Translates QGIS styles to various formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-09
        copyright            : (C) 2024 by Pietro Laba
        email                : pietrolabacm@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BabelStyler class from file BabelStyler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .babel_styler import BabelStyler
    return BabelStyler(iface)
